# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go
# Template requirements: *.go and go.mod files in directory

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo apt update
    sudo apt install apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    sudo apt install docker-ce
    sudo docker info
  displayName: Docker Install


- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    repository: 'cc-api-prueba-golang-snapshot'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: '0.1'
    buildContext: '**'
    addPipelineData: false

- task: Docker@2
  displayName: 'Save Docker Image'
  inputs:
    repository: 'cc-api-prueba-golang-snapshot'
    command: 'save'
    arguments: '-o $(Build.ArtifactStagingDirectory)/cc-api-prueba-golang-snapshot.image.tar cc-api-prueba-golang-snapshot:0.1'
    addPipelineData: false

- task: PublishBuildArtifacts@1
  displayName: 'Upload Docker Image'
  inputs:
   path: '$(Build.ArtifactStagingDirectory)'
   artifact: 'Build'
